version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: db-sigeduc-chamados
    restart: always
    networks:
      - sigeduc-chamados-network
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  sigeduc-chamados-network:
    driver: bridge
    name: sigeduc-chamados-network
